### ISSUE TITLE
Siden fungerer ikke 

### ISSUE THREAD

**Issue by hsvika** [Project-Lavinia/project-lavinia.github.io#12]
Får bare opp denne feilmeldingen: Hmm… kan ikke nå denne siden lavinia.no nektet å koble til.

**Comment by Log234** [comment]
Hei, vi undersøker problemet. Legger inn oppdatering her når vi vet mer.

**Comment by Log234** [comment]
Problemet er løst, så nå skal https://lavinia.no være oppe igjen.

**Comment by hsvika** [comment]
Tusen takk!
