### ISSUE TITLE
Incorrect mathematical representation of Hare's quota

### ISSUE THREAD

**Issue by Log234** [Project-Lavinia/project-lavinia.github.io#8]
![image](https://user-images.githubusercontent.com/2419963/90606760-8bb51800-e200-11ea-9077-521fd11c7b98.png)
Should be:
![image](https://user-images.githubusercontent.com/2419963/90606790-966fad00-e200-11ea-877b-2ef01f7e79f7.png)

**Comment by oysor** [comment]
Fixed.
